package pl.luxdev.mbot.events;

public enum EventType {
	TEXT_MESSAGE_EVENT, CLIENT_JOIN_EVENT, CLIENT_LEAVE_EVENT, SERVER_EDITED_EVENT, CHANNEL_EDITED_EVENT, CHANNEL_DESCRIPTION_EDITED_EVENT, CLIENT_MOVED_EVENT, CHANNEL_CREATE_EVENT, CHANNEL_DELETED_EVENT, CHANNEL_MOVED_EVENT, CHANNEL_PASSWORD_CHANGED_EVENT, PRIVILEGE_KEY_USED_EVENT
}
